### ISSUE TITLE
Add PR-template

### ISSUE THREAD

**Issue by sindrehan** [BluEye-Robotics/blueye.sdk#15]
Needs to include reminder to run Hardware-in-the-loop tests before merging.

**Comment by soulspark666** [comment]
**Something like this will be good enough??**










**Description**


**Related Issue**


**Checklist**


- [ ] run `Hardware-in-the-loop` tests.

**Comment by sindrehan** [comment]
Hi,
Sorry that this issue isn't more specific, it was mostly left as a reminder to ourselves.

However, what you've proposed there is pretty close to what we're looking for, so if you want you can open a pull request, and we'll put the final touches on it there.

**Comment by soulspark666** [comment]
please check out #25
