### ISSUE TITLE
Reduce gif sizes in documentation, or preview a Youtube video instead

### ISSUE THREAD

**Issue by aksell** [BluEye-Robotics/blueye.sdk#21]
As Sindre pointed out the two gifs in the documentation are both large (66 and 30 MB)

> This gif is very large (66M!). For the documentation it would be better to inline the youtube video it's pulled from, but if we're merging this file and the README then we need to think of something else, as Github Markdown strips iframes when rendering html

>This gif is also quite large (30M), should try and see if we can compress it some more without losing too much quality.

See: https://github.com/BluEye-Robotics/blueye.sdk/pull/18#discussion_r329450176

**Comment by sindrehan** [comment]
I managed to compress the SDK demo gif down to ~9MB (which is below the limit for images in Github markdown), but I was not able to do the same for the Tautra-gif, so I've removed it from the README and added a preview-image for the spec-video instead.
