### ISSUE TITLE
Add python 3.8 to the test matrix

### ISSUE THREAD

**Issue by sindrehan** [BluEye-Robotics/blueye.sdk#42]
The stable version of Python 3.8 was released on the 14th of October so we should add it to the test matrix in Github Actions to ensure that nothing breaks with the new version.

Currently Python 3.8 is not included in the python-action, but it should be included soon, see [this comment](https://github.com/actions/setup-python/issues/30#issuecomment-546974397)

**Comment by hugovk** [comment]
https://github.com/actions/setup-python/issues/30 is now ready.
