### ISSUE TITLE
Document installation instructions for Windows

### ISSUE THREAD

**Issue by sindrehan** [BluEye-Robotics/blueye.sdk#5]

**Comment by soulspark666** [comment]
What kind of documentation do you require???

**Comment by sindrehan** [comment]
Hi Animesh, thank you for wanting to contribute to our SDK!

I've just now made [a commit](https://github.com/BluEye-Robotics/blueye.sdk/commit/08d6c6642a5e1eca2546abbe66329fb08b574ee0) that restructures we would like the documentation for installation to various OSs to be. 

If you want, you are welcome to take a stab at the Windows documenation, though it might be a bit difficult if you don't have a drone. However, if you are able to instantiate a Pioneer-object with `autoconnect=False` without crashing then we should be pretty close.

As to what documentation we require, I think something close to what we have for Linux/Ubuntu right now would be nice. since pyenv doesn't work on Windows, we should find a suitable replacement for it, [pyenv-win](https://github.com/pyenv-win/pyenv-win) looks promising, but I haven't tested it.

Let me know if you have any other questions, and I'll do my best to help out.

**Comment by sindrehan** [comment]
Fixed in #27
